# Back Propagation Illustration

two layer fully connected network

In [1]:
import numpy as np

In [29]:
input_size = 4
hidden_size = 10
num_classes = 3
num_inputs = 5
N= 5

In [16]:
x = np.random.rand(num_inputs,input_size)
h1 = np.random.rand(input_size,hidden_size)
h2 = np.random.rand(hidden_size,num_classes)
b1= np.random.rand(1,hidden_size)
b2 = np.random.rand(1,num_classes)

In [17]:
x

array([[0.68601668, 0.43656707, 0.18775476, 0.9230418 ],
       [0.22996683, 0.04873868, 0.94584478, 0.21207473],
       [0.49786743, 0.19018346, 0.308208  , 0.67710977],
       [0.77302765, 0.3962753 , 0.02861088, 0.42965049],
       [0.69239226, 0.37192737, 0.04115848, 0.92473483]])

In [18]:
h1

array([[0.56867403, 0.77216369, 0.13734916, 0.48985373, 0.21555271,
        0.92919049, 0.94924823, 0.52394269, 0.89431119, 0.24018398],
       [0.33206145, 0.55485482, 0.18366402, 0.75198737, 0.81829092,
        0.15671713, 0.23016427, 0.92291967, 0.43191418, 0.63042281],
       [0.91980807, 0.3750707 , 0.64042941, 0.7479426 , 0.0372577 ,
        0.18772193, 0.36632696, 0.65616221, 0.37086623, 0.68261622],
       [0.23541433, 0.31593232, 0.34065806, 0.05922922, 0.38655499,
        0.45326226, 0.98250419, 0.50349624, 0.56298428, 0.48558978]])

In [19]:
b1

array([[0.04862987, 0.1115794 , 0.42092916, 0.8231059 , 0.87366062,
        0.70924241, 0.65900507, 0.49475792, 0.05713816, 0.78595603]])

In [44]:
z= np.dot(x,h1)+b1
resp1 = np.where(z>0,z,0)

In [45]:
scores= np.dot(resp1,h2)+b2

In [46]:
scores

array([[ 8.95415327, 10.59321081,  8.56874197],
       [ 6.92689158,  7.77378196,  6.87705954],
       [ 7.60566399,  8.68234475,  7.16933165],
       [ 7.54551933,  8.84569979,  7.33189682],
       [ 8.49986293,  9.95067232,  7.99171963]])

In [47]:
y=[0,1,2,2,1]

f = scores to reduce max score of each column( each test data point)

In [22]:
f = scores.T - np.max(scores,axis=1)
f

array([[-1.63905754, -0.84689038, -1.07668076, -1.30018046, -1.45080939],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [-2.02446885, -0.89672242, -1.5130131 , -1.51380297, -1.9589527 ]])

- Use softmax to convert model score to probability. 
- Each column is a data point with probability for each class. 
- e.g. 0.23 for class 1, 0.53 for class 2 and 0.22 for class 3

In [27]:
f = np.exp(f)
p = f/np.sum(f,axis=0)
p

array([[0.23932838, 0.26667665, 0.26178789, 0.24882592, 0.24623395],
       [0.53575323, 0.47214718, 0.50613832, 0.51505356, 0.52948328],
       [0.22491839, 0.26117617, 0.23207378, 0.23612052, 0.22428277]])

In [31]:
_sample_ix  = np.arange(N)
_sample_ix

array([0, 1, 2, 3, 4])

- Use the pair of row=y[i] and column=i to deduce the probability for ground truth. 
- So if y[0] is class 0, then the true class will get its probability reduced by 1. 

In [32]:
grads={}
df = p
df[y,_sample_ix]-=1
df

array([[-0.76067162,  0.26667665,  0.26178789,  0.24882592,  0.24623395],
       [ 0.53575323, -0.52785282,  0.50613832,  0.51505356, -0.47051672],
       [ 0.22491839,  0.26117617, -0.76792622, -0.76387948,  0.22428277]])

In [39]:
df[y[0],0]

-0.760671615611053

In [40]:
df[y[1],1]

-0.527852818852556

- W2 is of dimension(hidden_size, class_size)
- df is estimation loss
- score = z * w2 + b2, so the df/dw2 = z 

In [42]:
dw2 = df.dot(z).T/N
grads['W2']=dw2
dw2

array([[ 0.03286772,  0.07105576, -0.10392348],
       [ 0.00923748,  0.15134869, -0.16058617],
       [ 0.03756917,  0.07811826, -0.11568743],
       [ 0.06400701,  0.16707231, -0.23107932],
       [ 0.02559751,  0.21448086, -0.24007837],
       [ 0.03654069,  0.23279042, -0.26933112],
       [ 0.02612272,  0.27967121, -0.30579393],
       [ 0.02857706,  0.19566899, -0.22424605],
       [ 0.00233791,  0.17648344, -0.17882134],
       [ 0.04823555,  0.17317155, -0.2214071 ]])

In [43]:
db2 = np.mean(df,axis=1)
grads['b2']=db2
db2

array([ 0.05257056,  0.11171512, -0.16428567])

In [51]:
dresp1 = h2.dot(df)/N
dz = np.where(z>0,resp1,0)
dw1= x.T.dot(dz)
grads['W1']=dw1
dw1

array([[2.48804881, 3.12189996, 2.67475632, 4.53382942, 4.49737762,
        4.91746661, 6.03337418, 4.65135943, 3.56145544, 4.6607106 ],
       [1.240437  , 1.61424288, 1.33359836, 2.27963354, 2.31566885,
        2.52554858, 3.10811169, 2.37798335, 1.84961204, 2.35666856],
       [1.55132574, 1.29731437, 1.62462102, 2.48012167, 1.89674902,
        2.09666115, 2.5659043 , 2.22592579, 1.40807203, 2.46336641],
       [2.783308  , 3.47129878, 3.02174659, 4.99158047, 5.0096163 ,
        5.46639502, 6.80552149, 5.20628421, 4.00137997, 5.22818327]])

In [52]:
db1 = np.sum(dz,axis=0)
grads['b1']=db1
db1

array([ 4.49573671,  5.14958793,  4.81205556,  7.92971781,  7.45068514,
        8.16691609, 10.02539494,  7.90099085,  5.82755135,  8.10097233])