In [1]:
import numpy as np

### 1 Forward Pass

In [3]:
input_size = 4
hidden_size = 10
num_classes = 3
num_inputs = 5

In [4]:
x = np.random.rand(1,4)
h1 = np.random.rand(4,10)
h2 = np.random.rand(10,3)

In [10]:
print(x)
print(h1)

[[0.47652309 0.44267149 0.92751228 0.37625421]]
[[0.14381708 0.37910398 0.37107567 0.54190151 0.56289133 0.12119121
  0.3448073  0.92259336 0.73150979 0.82647783]
 [0.71821742 0.72019272 0.78142657 0.58099888 0.82642908 0.58546644
  0.80229935 0.36454112 0.56214378 0.85751677]
 [0.1565883  0.89470632 0.47531718 0.93348549 0.58124293 0.39220211
  0.29622631 0.77346681 0.94393093 0.16625974]
 [0.23957184 0.6285343  0.69231099 0.34544739 0.86939279 0.43478021
  0.86119666 0.40824688 0.89174895 0.84734684]]


In [6]:
layer1 = x.dot(h1)
layer2 = layer1.dot(h2)

In [7]:
layer1

array([[0.62184401, 1.56580035, 1.22408883, 1.5112155 , 1.50028995,
        0.84427987, 1.11824609, 1.47201356, 1.80845815, 1.24645975]])

In [9]:
layer2

array([[6.11931794, 8.41992156, 6.09863927]])